version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      PORT: 8080  # Default port, can be overridden
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: webapp
    command: CompileDaemon --build="go build -o main" --command="./main"
    container_name: webapp
    volumes:
      - .:/app
    working_dir: /app
    restart: always

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/1.sql
